# Generated by Django 5.1.7 on 2025-03-26 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_address_customuser_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='additional_managers',
            field=models.ManyToManyField(blank=True, help_text='Additional managers for this user', related_name='additional_direct_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Primary manager for staff and superuser accounts', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='no_manager',
            field=models.BooleanField(default=False, help_text='Check if this user does not require a manager'),
        ),
    ]
