# Generated by Django 5.1.7 on 2025-04-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_adminsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='manually_modified',
            field=models.BooleanField(default=False, help_text='Indicates if user was manually modified in admin'),
        ),
    ]
