# Generated by Django 5.1.7 on 2025-03-16 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='violation',
            options={'ordering': ['standard', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='violation',
            unique_together={('standard', 'name')},
        ),
        migrations.RemoveField(
            model_name='violation',
            name='code',
        ),
        migrations.RemoveField(
            model_name='violation',
            name='severity',
        ),
    ]
