# Generated by Django 5.1.7 on 2025-03-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_description_remove_project_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='status_choices',
            field=models.JSONField(blank=True, default=list, help_text="List of status choices for this project type in format [['key', 'Display Name'], ...]"),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='not_started', max_length=50),
        ),
    ]
