# Generated by Django 5.1.7 on 2025-03-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projecttype_status_choices_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='milestone_choices',
            field=models.JSONField(blank=True, default=list, help_text="List of milestone choices for this project type in format [['key', 'Display Name'], ...]"),
        ),
    ]
