# Generated by Django 5.1.7 on 2025-03-16 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projecttype_milestone_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_standards', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_standards', to='projects.project')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_instances', to='projects.standard')),
            ],
            options={
                'ordering': ['standard__name', 'standard__version'],
                'unique_together': {('project', 'standard')},
            },
        ),
    ]
