# Generated by Django 5.1.7 on 2025-03-16 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectstandard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectstandard',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='projectstandard',
            constraint=models.UniqueConstraint(fields=('project',), name='one_standard_per_project'),
        ),
    ]
