# Generated by Django 5.1.7 on 2025-03-16 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_milestone_assigned_to_milestone_milestone_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='issue_fields',
            field=models.JSONField(blank=True, default=list, help_text="List of custom issue fields for this project type in format [{'name': 'field_name', 'type': 'field_type', 'required': true/false, 'choices': [['key', 'Display Name'], ...]}]"),
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField()),
                ('steps_to_reproduce', models.TextField()),
                ('tool_or_method', models.CharField(choices=[('jaws', 'JAWS'), ('nvda', 'NVDA'), ('cca', 'CCA'), ('zoomtext', 'ZoomText'), ('voiceover', 'VoiceOver'), ('talkback', 'Talkback'), ('wave', 'WAVE'), ('accessibility_insights', 'Accessibility Insights'), ('other', 'Other')], max_length=50)),
                ('user_impact', models.CharField(choices=[('high', 'High'), ('low', 'Low'), ('best_practice', 'Best Practice')], max_length=20)),
                ('user_impact_description', models.TextField()),
                ('workarounds', models.TextField(blank=True)),
                ('current_status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('qa', 'QA'), ('in_remediation', 'In Remediation'), ('ready_for_testing', 'Ready For Testing')], default='fail', max_length=20)),
                ('dynamic_fields', models.JSONField(blank=True, default=dict, help_text='Dynamic fields based on project type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_issues', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.milestone')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.page')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.project')),
                ('violation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.violation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
