# Generated by Django 5.1.7 on 2025-03-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projecttype_issue_fields_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(blank=True, help_text='Type of issue based on project type', max_length=100),
        ),
    ]
