# Generated by Django 5.1.7 on 2025-03-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_issue_issue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='issue_type_choices',
            field=models.JSONField(blank=True, default=list, help_text="List of issue type choices for this project type in format [['key', 'Display Name'], ...]"),
        ),
    ]
