# Generated by Django 5.1.7 on 2025-03-16 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_issue_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='issue_type',
        ),
        migrations.RemoveField(
            model_name='projecttype',
            name='issue_type_choices',
        ),
    ]
