# Generated by Django 5.1.7 on 2025-03-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_remove_issue_type_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='attachment',
            field=models.FileField(blank=True, help_text='File attachment for this issue', null=True, upload_to='issue_attachments/'),
        ),
    ]
