# Generated by Django 5.1.7 on 2025-03-16 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_issuecomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='projects.milestone'),
        ),
        migrations.AddField(
            model_name='comment',
            name='new_status',
            field=models.CharField(blank=True, help_text='New status after change', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='previous_status',
            field=models.CharField(blank=True, help_text='Previous status before change', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='status_changed',
            field=models.BooleanField(default=False, help_text='Whether this comment included a status change'),
        ),
        migrations.CreateModel(
            name='IssueModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification_type', models.CharField(help_text='Type of modification (status change, comment, etc.)', max_length=50)),
                ('previous_value', models.TextField(blank=True, help_text='Previous value before change', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value after change', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications', to='projects.comment')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='projects.issue')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_modifications', to='projects.milestone')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_modifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
