# Generated by Django 5.1.7 on 2025-03-16 22:44

from django.db import migrations
from django.contrib.auth.management import create_permissions


def add_migration_message(apps, schema_editor):
    """Add a message about the new features"""
    # This is just a placeholder for documentation purposes
    print("Migration complete: Added tracking of issue modifications and milestone comments")
    print("New features:")
    print("1. Comments now track which milestone they were made in")
    print("2. Status changes are recorded with previous and new values")
    print("3. All modifications are tracked in the IssueModification model")
    print("4. Milestone detail page now shows recently modified issues")


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_comment_milestone_comment_new_status_and_more'),
    ]

    operations = [
        migrations.RunPython(add_migration_message, migrations.RunPython.noop),
    ]
